# This is a basic workflow to help you get started with Actions

name: GitHub API Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      
      - name: Run Newman API Tests
        run: |
          newman run "./GitHubAPI.postman_collection.json" \
            --global-var "GitHub_Token=${{ secrets.TOKEN }}" \
            --global-var "base_url=https://api.github.com" \
            --global-var "owner=FerasWT" \
            --global-var "repo=api-testing-demo" \
            --global-var "Issue_Number=4"\
            -n 2 \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/report.html
      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman
