# This is a basic workflow to help you get started with Actions

name: GitHub API Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Newman API Tests
        run: |
          newman run "./GitHubAPI.postman_collection.json" \
            --global-var "GitHub_Token=${{ secrets.TOKEN }}" \
            --global-var "base_url=https://api.github.com" \
            --global-var "owner=FerasWT" \
            --global-var "repo=api-testing-demo" \
            --global-var "Issue_Number=4"
